apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-app
  template:
    metadata:
      labels:
        app: hello-app
    spec:
      containers:
      - name: hello-app
        # Use seu usuário do Docker Hub. Esta linha será
        # atualizada automaticamente pelo GitHub Actions.
        image: andreviniciusdevops/hello-app:sha-923d477
        ports:
        - containerPort: 8000